const fs=require("fs")
const zlib=require("zlib")
// console.log(zlib)
const readStream=fs.createReadStream("../data/sample.txt")
const writeStream=fs.createWriteStream("../data/samplecompresseddeflate.txt.deflate")
// const gzip=zlib.createGzip()
// readStream.pipe(gzip).pipe(writeStream)
// const brotli=zlib.createBrotliCompress()
// readStream.pipe(brotli).pipe(writeStream)
const deflate=zlib.createDeflate()
readStream.pipe(deflate).pipe(writeStream)