const fs=require("fs")
// const writeStream=fs.createWriteStream("../data/file.txt",{flags:'a'})
// writeStream.write("this is a new line")
// writeStream.write("\n")
// writeStream.write("this is a new line")
// writeStream.write("\n")
// writeStream.write("this is a new line")
// writeStream.write("\n")
// writeStream.on("error",(err)=>console.log(err))
